// Generated by scripts/import-general-vocabulary.mjs. Do not edit by hand.
import type { GeneralVocabularySourceEntry, GeneralVocabularySourceMetadata } from "./general-vocabulary-types.ts";

export const generalVocabularySourceMetadata = {
  "title": "Words",
  "sourceFileName": "Words 3b5c9f835a8d808d9673f3f598c2022a.md",
  "sourceSha256": "c173fc51f0a54393b3942b6d04ae600fd8570a71768b07089642ba78e7db7eea",
  "claimedEntryCount": 500,
  "actualEntryCount": 351
} as const satisfies GeneralVocabularySourceMetadata;

export const generalVocabularySourceEntries = [
  {
    "id": "general-vocabulary:verb:ter",
    "partOfSpeech": "verb",
    "portuguese": "ter",
    "translation": "иметь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:haver",
    "partOfSpeech": "verb",
    "portuguese": "haver",
    "translation": "иметься, существовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:vir",
    "partOfSpeech": "verb",
    "portuguese": "vir",
    "translation": "приходить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:dizer",
    "partOfSpeech": "verb",
    "portuguese": "dizer",
    "translation": "сказать, говорить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:poder",
    "partOfSpeech": "verb",
    "portuguese": "poder",
    "translation": "мочь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:dever",
    "partOfSpeech": "verb",
    "portuguese": "dever",
    "translation": "быть должным",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:ficar",
    "partOfSpeech": "verb",
    "portuguese": "ficar",
    "translation": "оставаться, находиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:passar",
    "partOfSpeech": "verb",
    "portuguese": "passar",
    "translation": "проходить, проводить (время)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:chegar",
    "partOfSpeech": "verb",
    "portuguese": "chegar",
    "translation": "прибывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:levar",
    "partOfSpeech": "verb",
    "portuguese": "levar",
    "translation": "нести, уносить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:trazer",
    "partOfSpeech": "verb",
    "portuguese": "trazer",
    "translation": "приносить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:deixar",
    "partOfSpeech": "verb",
    "portuguese": "deixar",
    "translation": "оставлять, позволять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:encontrar",
    "partOfSpeech": "verb",
    "portuguese": "encontrar",
    "translation": "находить, встречать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:pensar",
    "partOfSpeech": "verb",
    "portuguese": "pensar",
    "translation": "думать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:achar",
    "partOfSpeech": "verb",
    "portuguese": "achar",
    "translation": "считать, находить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:voltar",
    "partOfSpeech": "verb",
    "portuguese": "voltar",
    "translation": "возвращаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:levantar-se",
    "partOfSpeech": "verb",
    "portuguese": "levantar-se",
    "translation": "вставать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:deitar-se",
    "partOfSpeech": "verb",
    "portuguese": "deitar-se",
    "translation": "ложиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acordar",
    "partOfSpeech": "verb",
    "portuguese": "acordar",
    "translation": "просыпаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:vender",
    "partOfSpeech": "verb",
    "portuguese": "vender",
    "translation": "продавать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:pagar",
    "partOfSpeech": "verb",
    "portuguese": "pagar",
    "translation": "платить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:gastar",
    "partOfSpeech": "verb",
    "portuguese": "gastar",
    "translation": "тратить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:ensinar",
    "partOfSpeech": "verb",
    "portuguese": "ensinar",
    "translation": "обучать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:escutar",
    "partOfSpeech": "verb",
    "portuguese": "escutar",
    "translation": "слушать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cantar",
    "partOfSpeech": "verb",
    "portuguese": "cantar",
    "translation": "петь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:dancar",
    "partOfSpeech": "verb",
    "portuguese": "dançar",
    "translation": "танцевать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:perder",
    "partOfSpeech": "verb",
    "portuguese": "perder",
    "translation": "терять, проигрывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:precisar",
    "partOfSpeech": "verb",
    "portuguese": "precisar",
    "translation": "нуждаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:amar",
    "partOfSpeech": "verb",
    "portuguese": "amar",
    "translation": "любить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:odiar",
    "partOfSpeech": "verb",
    "portuguese": "odiar",
    "translation": "ненавидеть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sentir",
    "partOfSpeech": "verb",
    "portuguese": "sentir",
    "translation": "чувствовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:morrer",
    "partOfSpeech": "verb",
    "portuguese": "morrer",
    "translation": "умирать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:mudar",
    "partOfSpeech": "verb",
    "portuguese": "mudar",
    "translation": "менять(ся)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:mover",
    "partOfSpeech": "verb",
    "portuguese": "mover",
    "translation": "двигать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tocar",
    "partOfSpeech": "verb",
    "portuguese": "tocar",
    "translation": "трогать, играть на инструменте",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:pegar",
    "partOfSpeech": "verb",
    "portuguese": "pegar",
    "translation": "брать, хватать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:segurar",
    "partOfSpeech": "verb",
    "portuguese": "segurar",
    "translation": "держать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:soltar",
    "partOfSpeech": "verb",
    "portuguese": "soltar",
    "translation": "отпускать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:lancar",
    "partOfSpeech": "verb",
    "portuguese": "lançar",
    "translation": "бросать, запускать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:subir",
    "partOfSpeech": "verb",
    "portuguese": "subir",
    "translation": "подниматься",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:descer",
    "partOfSpeech": "verb",
    "portuguese": "descer",
    "translation": "спускаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:viajar",
    "partOfSpeech": "verb",
    "portuguese": "viajar",
    "translation": "путешествовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:conduzir",
    "partOfSpeech": "verb",
    "portuguese": "conduzir",
    "translation": "водить машину",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:dirigir",
    "partOfSpeech": "verb",
    "portuguese": "dirigir",
    "translation": "управлять, вести",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:caminhar",
    "partOfSpeech": "verb",
    "portuguese": "caminhar",
    "translation": "идти пешком",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:procurar",
    "partOfSpeech": "verb",
    "portuguese": "procurar",
    "translation": "искать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:encontrar-se",
    "partOfSpeech": "verb",
    "portuguese": "encontrar-se",
    "translation": "встречаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:conhecer",
    "partOfSpeech": "verb",
    "portuguese": "conhecer",
    "translation": "быть знакомым, знать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:reconhecer",
    "partOfSpeech": "verb",
    "portuguese": "reconhecer",
    "translation": "узнавать, признавать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:lembrar",
    "partOfSpeech": "verb",
    "portuguese": "lembrar",
    "translation": "помнить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:imaginar",
    "partOfSpeech": "verb",
    "portuguese": "imaginar",
    "translation": "воображать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sonhar",
    "partOfSpeech": "verb",
    "portuguese": "sonhar",
    "translation": "мечтать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:decidir",
    "partOfSpeech": "verb",
    "portuguese": "decidir",
    "translation": "решать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tentar",
    "partOfSpeech": "verb",
    "portuguese": "tentar",
    "translation": "пытаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:conseguir",
    "partOfSpeech": "verb",
    "portuguese": "conseguir",
    "translation": "суметь, добиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tratar",
    "partOfSpeech": "verb",
    "portuguese": "tratar",
    "translation": "обращаться, лечить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cuidar",
    "partOfSpeech": "verb",
    "portuguese": "cuidar",
    "translation": "заботиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:proteger",
    "partOfSpeech": "verb",
    "portuguese": "proteger",
    "translation": "защищать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:salvar",
    "partOfSpeech": "verb",
    "portuguese": "salvar",
    "translation": "спасать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:matar",
    "partOfSpeech": "verb",
    "portuguese": "matar",
    "translation": "убивать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:lutar",
    "partOfSpeech": "verb",
    "portuguese": "lutar",
    "translation": "бороться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:vencer",
    "partOfSpeech": "verb",
    "portuguese": "vencer",
    "translation": "побеждать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:responder",
    "partOfSpeech": "verb",
    "portuguese": "responder",
    "translation": "отвечать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:explicar",
    "partOfSpeech": "verb",
    "portuguese": "explicar",
    "translation": "объяснять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:entender",
    "partOfSpeech": "verb",
    "portuguese": "entender",
    "translation": "понимать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:compreender",
    "partOfSpeech": "verb",
    "portuguese": "compreender",
    "translation": "понимать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:duvidar",
    "partOfSpeech": "verb",
    "portuguese": "duvidar",
    "translation": "сомневаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:concordar",
    "partOfSpeech": "verb",
    "portuguese": "concordar",
    "translation": "соглашаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:discordar",
    "partOfSpeech": "verb",
    "portuguese": "discordar",
    "translation": "не соглашаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:discutir",
    "partOfSpeech": "verb",
    "portuguese": "discutir",
    "translation": "обсуждать, спорить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:conversar",
    "partOfSpeech": "verb",
    "portuguese": "conversar",
    "translation": "беседовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:contar",
    "partOfSpeech": "verb",
    "portuguese": "contar",
    "translation": "рассказывать, считать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:esconder",
    "partOfSpeech": "verb",
    "portuguese": "esconder",
    "translation": "прятать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:guardar",
    "partOfSpeech": "verb",
    "portuguese": "guardar",
    "translation": "хранить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:manter",
    "partOfSpeech": "verb",
    "portuguese": "manter",
    "translation": "сохранять, поддерживать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:continuar",
    "partOfSpeech": "verb",
    "portuguese": "continuar",
    "translation": "продолжать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:iniciar",
    "partOfSpeech": "verb",
    "portuguese": "iniciar",
    "translation": "начинать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:destruir",
    "partOfSpeech": "verb",
    "portuguese": "destruir",
    "translation": "разрушать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:quebrar",
    "partOfSpeech": "verb",
    "portuguese": "quebrar",
    "translation": "ломать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:reparar",
    "partOfSpeech": "verb",
    "portuguese": "reparar",
    "translation": "чинить, замечать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:secar",
    "partOfSpeech": "verb",
    "portuguese": "secar",
    "translation": "сушить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cozer",
    "partOfSpeech": "verb",
    "portuguese": "cozer",
    "translation": "варить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:fritar",
    "partOfSpeech": "verb",
    "portuguese": "fritar",
    "translation": "жарить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:assar",
    "partOfSpeech": "verb",
    "portuguese": "assar",
    "translation": "печь, жарить в духовке",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cortar",
    "partOfSpeech": "verb",
    "portuguese": "cortar",
    "translation": "резать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:misturar",
    "partOfSpeech": "verb",
    "portuguese": "misturar",
    "translation": "смешивать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:juntar",
    "partOfSpeech": "verb",
    "portuguese": "juntar",
    "translation": "соединять, собирать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:separar",
    "partOfSpeech": "verb",
    "portuguese": "separar",
    "translation": "разделять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:dividir",
    "partOfSpeech": "verb",
    "portuguese": "dividir",
    "translation": "делить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:abracar",
    "partOfSpeech": "verb",
    "portuguese": "abraçar",
    "translation": "обнимать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:beijar",
    "partOfSpeech": "verb",
    "portuguese": "beijar",
    "translation": "целовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sorrir",
    "partOfSpeech": "verb",
    "portuguese": "sorrir",
    "translation": "улыбаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:rir",
    "partOfSpeech": "verb",
    "portuguese": "rir",
    "translation": "смеяться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sussurrar",
    "partOfSpeech": "verb",
    "portuguese": "sussurrar",
    "translation": "шептать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:calar-se",
    "partOfSpeech": "verb",
    "portuguese": "calar-se",
    "translation": "замолчать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:respirar",
    "partOfSpeech": "verb",
    "portuguese": "respirar",
    "translation": "дышать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:relaxar",
    "partOfSpeech": "verb",
    "portuguese": "relaxar",
    "translation": "расслабляться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cansar-se",
    "partOfSpeech": "verb",
    "portuguese": "cansar-se",
    "translation": "уставать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acontecer",
    "partOfSpeech": "verb",
    "portuguese": "acontecer",
    "translation": "происходить, случаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:permitir",
    "partOfSpeech": "verb",
    "portuguese": "permitir",
    "translation": "разрешать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:proibir",
    "partOfSpeech": "verb",
    "portuguese": "proibir",
    "translation": "запрещать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:impedir",
    "partOfSpeech": "verb",
    "portuguese": "impedir",
    "translation": "препятствовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:evitar",
    "partOfSpeech": "verb",
    "portuguese": "evitar",
    "translation": "избегать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:arriscar",
    "partOfSpeech": "verb",
    "portuguese": "arriscar",
    "translation": "рисковать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:organizar",
    "partOfSpeech": "verb",
    "portuguese": "organizar",
    "translation": "организовывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:vestir",
    "partOfSpeech": "verb",
    "portuguese": "vestir",
    "translation": "одевать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:despir",
    "partOfSpeech": "verb",
    "portuguese": "despir",
    "translation": "раздевать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:calcar",
    "partOfSpeech": "verb",
    "portuguese": "calçar",
    "translation": "обувать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:pentear",
    "partOfSpeech": "verb",
    "portuguese": "pentear",
    "translation": "расчёсывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:filmar",
    "partOfSpeech": "verb",
    "portuguese": "filmar",
    "translation": "снимать видео",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:gravar",
    "partOfSpeech": "verb",
    "portuguese": "gravar",
    "translation": "записывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:imprimir",
    "partOfSpeech": "verb",
    "portuguese": "imprimir",
    "translation": "печатать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:enviar",
    "partOfSpeech": "verb",
    "portuguese": "enviar",
    "translation": "отправлять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:entregar",
    "partOfSpeech": "verb",
    "portuguese": "entregar",
    "translation": "доставлять, вручать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:devolver",
    "partOfSpeech": "verb",
    "portuguese": "devolver",
    "translation": "возвращать вещь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:emprestar",
    "partOfSpeech": "verb",
    "portuguese": "emprestar",
    "translation": "одалживать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:pedir",
    "partOfSpeech": "verb",
    "portuguese": "pedir",
    "translation": "просить, заказывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:oferecer",
    "partOfSpeech": "verb",
    "portuguese": "oferecer",
    "translation": "предлагать, дарить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:convidar",
    "partOfSpeech": "verb",
    "portuguese": "convidar",
    "translation": "приглашать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:visitar",
    "partOfSpeech": "verb",
    "portuguese": "visitar",
    "translation": "посещать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:mudar-se",
    "partOfSpeech": "verb",
    "portuguese": "mudar-se",
    "translation": "переезжать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:alugar",
    "partOfSpeech": "verb",
    "portuguese": "alugar",
    "translation": "арендовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:reservar",
    "partOfSpeech": "verb",
    "portuguese": "reservar",
    "translation": "бронировать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:marcar",
    "partOfSpeech": "verb",
    "portuguese": "marcar",
    "translation": "назначать встречу",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:atrasar-se",
    "partOfSpeech": "verb",
    "portuguese": "atrasar-se",
    "translation": "опаздывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:apressar-se",
    "partOfSpeech": "verb",
    "portuguese": "apressar-se",
    "translation": "торопиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:demorar",
    "partOfSpeech": "verb",
    "portuguese": "demorar",
    "translation": "задерживаться, занимать время",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:durar",
    "partOfSpeech": "verb",
    "portuguese": "durar",
    "translation": "длиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:funcionar",
    "partOfSpeech": "verb",
    "portuguese": "funcionar",
    "translation": "функционировать, работать (о механизме)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:ligar",
    "partOfSpeech": "verb",
    "portuguese": "ligar",
    "translation": "включать, звонить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:desligar",
    "partOfSpeech": "verb",
    "portuguese": "desligar",
    "translation": "выключать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:apagar",
    "partOfSpeech": "verb",
    "portuguese": "apagar",
    "translation": "гасить, стирать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acender",
    "partOfSpeech": "verb",
    "portuguese": "acender",
    "translation": "зажигать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:carregar",
    "partOfSpeech": "verb",
    "portuguese": "carregar",
    "translation": "заряжать, нести",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:descarregar",
    "partOfSpeech": "verb",
    "portuguese": "descarregar",
    "translation": "разряжать, разгружать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:instalar",
    "partOfSpeech": "verb",
    "portuguese": "instalar",
    "translation": "устанавливать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:utilizar",
    "partOfSpeech": "verb",
    "portuguese": "utilizar",
    "translation": "использовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:usar",
    "partOfSpeech": "verb",
    "portuguese": "usar",
    "translation": "использовать, носить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:aproveitar",
    "partOfSpeech": "verb",
    "portuguese": "aproveitar",
    "translation": "пользоваться, наслаждаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:poupar",
    "partOfSpeech": "verb",
    "portuguese": "poupar",
    "translation": "экономить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:investir",
    "partOfSpeech": "verb",
    "portuguese": "investir",
    "translation": "инвестировать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:custar",
    "partOfSpeech": "verb",
    "portuguese": "custar",
    "translation": "стоить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:valer",
    "partOfSpeech": "verb",
    "portuguese": "valer",
    "translation": "иметь ценность",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:aumentar",
    "partOfSpeech": "verb",
    "portuguese": "aumentar",
    "translation": "увеличивать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:diminuir",
    "partOfSpeech": "verb",
    "portuguese": "diminuir",
    "translation": "уменьшать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:reduzir",
    "partOfSpeech": "verb",
    "portuguese": "reduzir",
    "translation": "сокращать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:melhorar",
    "partOfSpeech": "verb",
    "portuguese": "melhorar",
    "translation": "улучшать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:piorar",
    "partOfSpeech": "verb",
    "portuguese": "piorar",
    "translation": "ухудшать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:transformar",
    "partOfSpeech": "verb",
    "portuguese": "transformar",
    "translation": "превращать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tornar-se",
    "partOfSpeech": "verb",
    "portuguese": "tornar-se",
    "translation": "становиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acreditar",
    "partOfSpeech": "verb",
    "portuguese": "acreditar",
    "translation": "верить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:confiar",
    "partOfSpeech": "verb",
    "portuguese": "confiar",
    "translation": "доверять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:desconfiar",
    "partOfSpeech": "verb",
    "portuguese": "desconfiar",
    "translation": "не доверять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:suspeitar",
    "partOfSpeech": "verb",
    "portuguese": "suspeitar",
    "translation": "подозревать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:influenciar",
    "partOfSpeech": "verb",
    "portuguese": "influenciar",
    "translation": "влиять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:convencer",
    "partOfSpeech": "verb",
    "portuguese": "convencer",
    "translation": "убеждать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:persuadir",
    "partOfSpeech": "verb",
    "portuguese": "persuadir",
    "translation": "уговаривать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:recusar",
    "partOfSpeech": "verb",
    "portuguese": "recusar",
    "translation": "отказывать(ся)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:aceitar",
    "partOfSpeech": "verb",
    "portuguese": "aceitar",
    "translation": "принимать, соглашаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:rejeitar",
    "partOfSpeech": "verb",
    "portuguese": "rejeitar",
    "translation": "отвергать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:admitir",
    "partOfSpeech": "verb",
    "portuguese": "admitir",
    "translation": "допускать, признавать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:negar",
    "partOfSpeech": "verb",
    "portuguese": "negar",
    "translation": "отрицать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:confirmar",
    "partOfSpeech": "verb",
    "portuguese": "confirmar",
    "translation": "подтверждать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:garantir",
    "partOfSpeech": "verb",
    "portuguese": "garantir",
    "translation": "гарантировать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:prometer",
    "partOfSpeech": "verb",
    "portuguese": "prometer",
    "translation": "обещать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:jurar",
    "partOfSpeech": "verb",
    "portuguese": "jurar",
    "translation": "клясться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:mentir",
    "partOfSpeech": "verb",
    "portuguese": "mentir",
    "translation": "лгать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:enganar",
    "partOfSpeech": "verb",
    "portuguese": "enganar",
    "translation": "обманывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:trair",
    "partOfSpeech": "verb",
    "portuguese": "trair",
    "translation": "предавать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:perdoar",
    "partOfSpeech": "verb",
    "portuguese": "perdoar",
    "translation": "прощать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:agradecer",
    "partOfSpeech": "verb",
    "portuguese": "agradecer",
    "translation": "благодарить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:desculpar-se",
    "partOfSpeech": "verb",
    "portuguese": "desculpar-se",
    "translation": "извиняться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cumprimentar",
    "partOfSpeech": "verb",
    "portuguese": "cumprimentar",
    "translation": "приветствовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:despedir-se",
    "partOfSpeech": "verb",
    "portuguese": "despedir-se",
    "translation": "прощаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:apresentar",
    "partOfSpeech": "verb",
    "portuguese": "apresentar",
    "translation": "представлять (кого-то)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:casar-se",
    "partOfSpeech": "verb",
    "portuguese": "casar-se",
    "translation": "жениться, выходить замуж",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:divorciar-se",
    "partOfSpeech": "verb",
    "portuguese": "divorciar-se",
    "translation": "разводиться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:namorar",
    "partOfSpeech": "verb",
    "portuguese": "namorar",
    "translation": "встречаться (романтически)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:apaixonar-se",
    "partOfSpeech": "verb",
    "portuguese": "apaixonar-se",
    "translation": "влюбляться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:engravidar",
    "partOfSpeech": "verb",
    "portuguese": "engravidar",
    "translation": "забеременеть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:criar",
    "partOfSpeech": "verb",
    "portuguese": "criar",
    "translation": "создавать, растить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:educar",
    "partOfSpeech": "verb",
    "portuguese": "educar",
    "translation": "воспитывать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:obedecer",
    "partOfSpeech": "verb",
    "portuguese": "obedecer",
    "translation": "подчиняться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:desobedecer",
    "partOfSpeech": "verb",
    "portuguese": "desobedecer",
    "translation": "не подчиняться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:respeitar",
    "partOfSpeech": "verb",
    "portuguese": "respeitar",
    "translation": "уважать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:admirar",
    "partOfSpeech": "verb",
    "portuguese": "admirar",
    "translation": "восхищаться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:invejar",
    "partOfSpeech": "verb",
    "portuguese": "invejar",
    "translation": "завидовать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:cheirar",
    "partOfSpeech": "verb",
    "portuguese": "cheirar",
    "translation": "пахнуть, нюхать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:provar",
    "partOfSpeech": "verb",
    "portuguese": "provar",
    "translation": "пробовать на вкус",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:saborear",
    "partOfSpeech": "verb",
    "portuguese": "saborear",
    "translation": "смаковать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:engolir",
    "partOfSpeech": "verb",
    "portuguese": "engolir",
    "translation": "глотать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:mastigar",
    "partOfSpeech": "verb",
    "portuguese": "mastigar",
    "translation": "жевать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:adoecer",
    "partOfSpeech": "verb",
    "portuguese": "adoecer",
    "translation": "заболеть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:curar",
    "partOfSpeech": "verb",
    "portuguese": "curar",
    "translation": "лечить, вылечивать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sarar",
    "partOfSpeech": "verb",
    "portuguese": "sarar",
    "translation": "заживать, выздоравливать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tossir",
    "partOfSpeech": "verb",
    "portuguese": "tossir",
    "translation": "кашлять",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:espirrar",
    "partOfSpeech": "verb",
    "portuguese": "espirrar",
    "translation": "чихать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:sangrar",
    "partOfSpeech": "verb",
    "portuguese": "sangrar",
    "translation": "кровоточить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:magoar-se",
    "partOfSpeech": "verb",
    "portuguese": "magoar-se",
    "translation": "ушибиться, обидеться",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:ferir",
    "partOfSpeech": "verb",
    "portuguese": "ferir",
    "translation": "ранить",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:tremer",
    "partOfSpeech": "verb",
    "portuguese": "tremer",
    "translation": "дрожать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:suar",
    "partOfSpeech": "verb",
    "portuguese": "suar",
    "translation": "потеть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acabar-de",
    "partOfSpeech": "verb",
    "portuguese": "acabar de",
    "translation": "только что сделать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:deixar-de",
    "partOfSpeech": "verb",
    "portuguese": "deixar de",
    "translation": "перестать делать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:comecar-a",
    "partOfSpeech": "verb",
    "portuguese": "começar a",
    "translation": "начинать делать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:acostumar-se",
    "partOfSpeech": "verb",
    "portuguese": "acostumar-se",
    "translation": "привыкать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:verb:habituar-se",
    "partOfSpeech": "verb",
    "portuguese": "habituar-se",
    "translation": "привыкать",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:apartamento",
    "partOfSpeech": "noun",
    "portuguese": "apartamento",
    "translation": "квартира",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:sala",
    "partOfSpeech": "noun",
    "portuguese": "sala",
    "translation": "гостиная",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:espelho",
    "partOfSpeech": "noun",
    "portuguese": "espelho",
    "translation": "зеркало",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:chao",
    "partOfSpeech": "noun",
    "portuguese": "chão",
    "translation": "пол",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:teto",
    "partOfSpeech": "noun",
    "portuguese": "teto",
    "translation": "потолок",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:chave",
    "partOfSpeech": "noun",
    "portuguese": "chave",
    "translation": "ключ",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:mensagem",
    "partOfSpeech": "noun",
    "portuguese": "mensagem",
    "translation": "сообщение",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:revista",
    "partOfSpeech": "noun",
    "portuguese": "revista",
    "translation": "журнал",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:conta",
    "partOfSpeech": "noun",
    "portuguese": "conta",
    "translation": "счёт",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:emprego",
    "partOfSpeech": "noun",
    "portuguese": "emprego",
    "translation": "работа, должность",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:escritorio",
    "partOfSpeech": "noun",
    "portuguese": "escritório",
    "translation": "офис",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:empresa",
    "partOfSpeech": "noun",
    "portuguese": "empresa",
    "translation": "компания",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:reuniao",
    "partOfSpeech": "noun",
    "portuguese": "reunião",
    "translation": "собрание, встреча",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:salario",
    "partOfSpeech": "noun",
    "portuguese": "salário",
    "translation": "зарплата",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:cliente",
    "partOfSpeech": "noun",
    "portuguese": "cliente",
    "translation": "клиент",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:negocio",
    "partOfSpeech": "noun",
    "portuguese": "negócio",
    "translation": "дело, бизнес",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:loja",
    "partOfSpeech": "noun",
    "portuguese": "loja",
    "translation": "магазин",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:preco",
    "partOfSpeech": "noun",
    "portuguese": "preço",
    "translation": "цена",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:desconto",
    "partOfSpeech": "noun",
    "portuguese": "desconto",
    "translation": "скидка",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:camisa",
    "partOfSpeech": "noun",
    "portuguese": "camisa",
    "translation": "рубашка",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:jantar",
    "partOfSpeech": "noun",
    "portuguese": "jantar",
    "translation": "ужин",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:arroz",
    "partOfSpeech": "noun",
    "portuguese": "arroz",
    "translation": "рис",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:legume",
    "partOfSpeech": "noun",
    "portuguese": "legume",
    "translation": "овощ",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:vinho",
    "partOfSpeech": "noun",
    "portuguese": "vinho",
    "translation": "вино",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:azeite",
    "partOfSpeech": "noun",
    "portuguese": "azeite",
    "translation": "оливковое масло",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:rua",
    "partOfSpeech": "noun",
    "portuguese": "rua",
    "translation": "улица",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:aldeia",
    "partOfSpeech": "noun",
    "portuguese": "aldeia",
    "translation": "деревня",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:praca",
    "partOfSpeech": "noun",
    "portuguese": "praça",
    "translation": "площадь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:avenida",
    "partOfSpeech": "noun",
    "portuguese": "avenida",
    "translation": "проспект",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:ponte",
    "partOfSpeech": "noun",
    "portuguese": "ponte",
    "translation": "мост",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:estrada",
    "partOfSpeech": "noun",
    "portuguese": "estrada",
    "translation": "дорога, шоссе",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:barco",
    "partOfSpeech": "noun",
    "portuguese": "barco",
    "translation": "лодка, корабль",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:viagem",
    "partOfSpeech": "noun",
    "portuguese": "viagem",
    "translation": "путешествие",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:estacao",
    "partOfSpeech": "noun",
    "portuguese": "estação",
    "translation": "вокзал, станция",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:paragem",
    "partOfSpeech": "noun",
    "portuguese": "paragem",
    "translation": "остановка",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:doente",
    "partOfSpeech": "noun",
    "portuguese": "doente",
    "translation": "больной",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:doenca",
    "partOfSpeech": "noun",
    "portuguese": "doença",
    "translation": "болезнь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:remedio",
    "partOfSpeech": "noun",
    "portuguese": "remédio",
    "translation": "лекарство",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:dor",
    "partOfSpeech": "noun",
    "portuguese": "dor",
    "translation": "боль",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:saude",
    "partOfSpeech": "noun",
    "portuguese": "saúde",
    "translation": "здоровье",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:exame",
    "partOfSpeech": "noun",
    "portuguese": "exame",
    "translation": "экзамен",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:licao",
    "partOfSpeech": "noun",
    "portuguese": "lição",
    "translation": "урок (тема)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:marido",
    "partOfSpeech": "noun",
    "portuguese": "marido",
    "translation": "муж",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:esposa",
    "partOfSpeech": "noun",
    "portuguese": "esposa",
    "translation": "жена",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:pessoa",
    "partOfSpeech": "noun",
    "portuguese": "pessoa",
    "translation": "человек",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:gente",
    "partOfSpeech": "noun",
    "portuguese": "gente",
    "translation": "люди",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:coracao",
    "partOfSpeech": "noun",
    "portuguese": "coração",
    "translation": "сердце",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:corpo",
    "partOfSpeech": "noun",
    "portuguese": "corpo",
    "translation": "тело",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:objeto",
    "partOfSpeech": "noun",
    "portuguese": "objeto",
    "translation": "предмет",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:solucao",
    "partOfSpeech": "noun",
    "portuguese": "solução",
    "translation": "решение",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:pergunta",
    "partOfSpeech": "noun",
    "portuguese": "pergunta",
    "translation": "вопрос",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:resposta",
    "partOfSpeech": "noun",
    "portuguese": "resposta",
    "translation": "ответ",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:noticia",
    "partOfSpeech": "noun",
    "portuguese": "notícia",
    "translation": "новость",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:verdade",
    "partOfSpeech": "noun",
    "portuguese": "verdade",
    "translation": "правда",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:mentira",
    "partOfSpeech": "noun",
    "portuguese": "mentira",
    "translation": "ложь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:motivo",
    "partOfSpeech": "noun",
    "portuguese": "motivo",
    "translation": "причина",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:razao",
    "partOfSpeech": "noun",
    "portuguese": "razão",
    "translation": "причина, правота",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:exemplo",
    "partOfSpeech": "noun",
    "portuguese": "exemplo",
    "translation": "пример",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:momento",
    "partOfSpeech": "noun",
    "portuguese": "momento",
    "translation": "момент",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:morte",
    "partOfSpeech": "noun",
    "portuguese": "morte",
    "translation": "смерть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:sonho",
    "partOfSpeech": "noun",
    "portuguese": "sonho",
    "translation": "мечта, сон",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:medo",
    "partOfSpeech": "noun",
    "portuguese": "medo",
    "translation": "страх",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:alegria",
    "partOfSpeech": "noun",
    "portuguese": "alegria",
    "translation": "радость",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:tristeza",
    "partOfSpeech": "noun",
    "portuguese": "tristeza",
    "translation": "грусть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:raiva",
    "partOfSpeech": "noun",
    "portuguese": "raiva",
    "translation": "злость",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:surpresa",
    "partOfSpeech": "noun",
    "portuguese": "surpresa",
    "translation": "удивление",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:felicidade",
    "partOfSpeech": "noun",
    "portuguese": "felicidade",
    "translation": "счастье",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:amor",
    "partOfSpeech": "noun",
    "portuguese": "amor",
    "translation": "любовь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:odio",
    "partOfSpeech": "noun",
    "portuguese": "ódio",
    "translation": "ненависть",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:esperanca",
    "partOfSpeech": "noun",
    "portuguese": "esperança",
    "translation": "надежда",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:sorte",
    "partOfSpeech": "noun",
    "portuguese": "sorte",
    "translation": "удача",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:azar",
    "partOfSpeech": "noun",
    "portuguese": "azar",
    "translation": "невезение",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:arte",
    "partOfSpeech": "noun",
    "portuguese": "arte",
    "translation": "искусство",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:cultura",
    "partOfSpeech": "noun",
    "portuguese": "cultura",
    "translation": "культура",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:natureza",
    "partOfSpeech": "noun",
    "portuguese": "natureza",
    "translation": "природа",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:montanha",
    "partOfSpeech": "noun",
    "portuguese": "montanha",
    "translation": "гора",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:ar",
    "partOfSpeech": "noun",
    "portuguese": "ar",
    "translation": "воздух",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:gente-jovem",
    "partOfSpeech": "noun",
    "portuguese": "gente jovem",
    "translation": "молодёжь",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:vizinhanca",
    "partOfSpeech": "noun",
    "portuguese": "vizinhança",
    "translation": "соседство",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:bairro",
    "partOfSpeech": "noun",
    "portuguese": "bairro",
    "translation": "квартал, район",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:espaco",
    "partOfSpeech": "noun",
    "portuguese": "espaço",
    "translation": "пространство",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:mundo",
    "partOfSpeech": "noun",
    "portuguese": "mundo",
    "translation": "мир",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:pais",
    "partOfSpeech": "noun",
    "portuguese": "país",
    "translation": "страна",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:governo",
    "partOfSpeech": "noun",
    "portuguese": "governo",
    "translation": "правительство",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:lei",
    "partOfSpeech": "noun",
    "portuguese": "lei",
    "translation": "закон",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:guerra",
    "partOfSpeech": "noun",
    "portuguese": "guerra",
    "translation": "война",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:paz",
    "partOfSpeech": "noun",
    "portuguese": "paz",
    "translation": "мир (отсутствие войны)",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:sociedade",
    "partOfSpeech": "noun",
    "portuguese": "sociedade",
    "translation": "общество",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:economia",
    "partOfSpeech": "noun",
    "portuguese": "economia",
    "translation": "экономика",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:opiniao",
    "partOfSpeech": "noun",
    "portuguese": "opinião",
    "translation": "мнение",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:decisao",
    "partOfSpeech": "noun",
    "portuguese": "decisão",
    "translation": "решение",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:conselho",
    "partOfSpeech": "noun",
    "portuguese": "conselho",
    "translation": "совет",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:noun:apoio",
    "partOfSpeech": "noun",
    "portuguese": "apoio",
    "translation": "поддержка",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:jovem",
    "partOfSpeech": "adjective",
    "portuguese": "jovem",
    "translation": "молодой",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:feliz",
    "partOfSpeech": "adjective",
    "portuguese": "feliz",
    "translation": "счастливый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:ocupado",
    "partOfSpeech": "adjective",
    "portuguese": "ocupado",
    "translation": "занятой",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:livre",
    "partOfSpeech": "adjective",
    "portuguese": "livre",
    "translation": "свободный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:importante",
    "partOfSpeech": "adjective",
    "portuguese": "importante",
    "translation": "важный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:interessante",
    "partOfSpeech": "adjective",
    "portuguese": "interessante",
    "translation": "интересный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:chato",
    "partOfSpeech": "adjective",
    "portuguese": "chato",
    "translation": "скучный, надоедливый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:engracado",
    "partOfSpeech": "adjective",
    "portuguese": "engraçado",
    "translation": "смешной",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:serio",
    "partOfSpeech": "adjective",
    "portuguese": "sério",
    "translation": "серьёзный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:nervoso",
    "partOfSpeech": "adjective",
    "portuguese": "nervoso",
    "translation": "нервный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:barato",
    "partOfSpeech": "adjective",
    "portuguese": "barato",
    "translation": "дешёвый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:limpo",
    "partOfSpeech": "adjective",
    "portuguese": "limpo",
    "translation": "чистый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:sujo",
    "partOfSpeech": "adjective",
    "portuguese": "sujo",
    "translation": "грязный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:cheio",
    "partOfSpeech": "adjective",
    "portuguese": "cheio",
    "translation": "полный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:vazio",
    "partOfSpeech": "adjective",
    "portuguese": "vazio",
    "translation": "пустой",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:seco",
    "partOfSpeech": "adjective",
    "portuguese": "seco",
    "translation": "сухой",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:molhado",
    "partOfSpeech": "adjective",
    "portuguese": "molhado",
    "translation": "мокрый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:salgado",
    "partOfSpeech": "adjective",
    "portuguese": "salgado",
    "translation": "солёный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:amargo",
    "partOfSpeech": "adjective",
    "portuguese": "amargo",
    "translation": "горький",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:azedo",
    "partOfSpeech": "adjective",
    "portuguese": "azedo",
    "translation": "кислый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:macio",
    "partOfSpeech": "adjective",
    "portuguese": "macio",
    "translation": "мягкий",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:duro",
    "partOfSpeech": "adjective",
    "portuguese": "duro",
    "translation": "твёрдый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:pesado",
    "partOfSpeech": "adjective",
    "portuguese": "pesado",
    "translation": "тяжёлый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:leve",
    "partOfSpeech": "adjective",
    "portuguese": "leve",
    "translation": "лёгкий по весу",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:largo",
    "partOfSpeech": "adjective",
    "portuguese": "largo",
    "translation": "широкий",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:estreito",
    "partOfSpeech": "adjective",
    "portuguese": "estreito",
    "translation": "узкий",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:saudavel",
    "partOfSpeech": "adjective",
    "portuguese": "saudável",
    "translation": "здоровый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:inteligente",
    "partOfSpeech": "adjective",
    "portuguese": "inteligente",
    "translation": "умный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:estupido",
    "partOfSpeech": "adjective",
    "portuguese": "estúpido",
    "translation": "глупый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:gentil",
    "partOfSpeech": "adjective",
    "portuguese": "gentil",
    "translation": "добрый, любезный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:educado",
    "partOfSpeech": "adjective",
    "portuguese": "educado",
    "translation": "воспитанный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:antipatico",
    "partOfSpeech": "adjective",
    "portuguese": "antipático",
    "translation": "неприятный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:honesto",
    "partOfSpeech": "adjective",
    "portuguese": "honesto",
    "translation": "честный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:diferente",
    "partOfSpeech": "adjective",
    "portuguese": "diferente",
    "translation": "другой, отличный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:igual",
    "partOfSpeech": "adjective",
    "portuguese": "igual",
    "translation": "одинаковый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:mesmo",
    "partOfSpeech": "adjective",
    "portuguese": "mesmo",
    "translation": "тот же самый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:proprio",
    "partOfSpeech": "adjective",
    "portuguese": "próprio",
    "translation": "собственный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:pronto",
    "partOfSpeech": "adjective",
    "portuguese": "pronto",
    "translation": "готовый",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:seguro",
    "partOfSpeech": "adjective",
    "portuguese": "seguro",
    "translation": "безопасный, уверенный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adjective:perigoso",
    "partOfSpeech": "adjective",
    "portuguese": "perigoso",
    "translation": "опасный",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:fora",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "fora",
    "translation": "снаружи",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:muito",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "muito",
    "translation": "очень, много",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:pouco",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "pouco",
    "translation": "мало",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:bem",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "bem",
    "translation": "хорошо",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:mal",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "mal",
    "translation": "плохо",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:talvez",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "talvez",
    "translation": "возможно",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:tambem",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "também",
    "translation": "тоже",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:ainda",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "ainda",
    "translation": "ещё",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:outra-vez",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "outra vez",
    "translation": "снова",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:rapidamente",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "rapidamente",
    "translation": "быстро",
    "editorialStatus": "needs-review"
  },
  {
    "id": "general-vocabulary:adverb-or-other:devagar",
    "partOfSpeech": "adverb-or-other",
    "portuguese": "devagar",
    "translation": "медленно",
    "editorialStatus": "needs-review"
  }
] as const satisfies readonly GeneralVocabularySourceEntry[];
